name: Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.4.6  # Specify the Terraform version

      - name: Terraform Init
        run: |
           cd terraform 
           terraform init -backend-config=STORAGE_ACCOUNT_NAME: ${{STORAGE_ACCOUNT_NAME}} \
                          -backend-config="container_name=terraform" \
                          -backend-config="key=terraform.tfstate" \
                          -backend-config="access_key=${{ secrets.ACCESS_KEY }}"

      - name: Terraform Format
        run: | 
         cd terraform 
         terraform fmt 
        
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          directory: terraform

      - name: Terraform plan
        run: |
         cd terraform 
         terraform plan
      - name: Terraform Apply
        run: |
         cd terraform
         terraform apply -auto-approve
        
      - name: Terraform Destroy
        run: |
          cd terraform
          terraform destroy -auto-approve
